server:
  port: 10001
  servlet:
    context-path: /file-service

spring:
  application:
    name: upload-service
  datasource:
    username: root
    password: root
    url: jdbc:mysql:///gulimall_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
minio:
  accessKey: pbjjFcF0FMHQoxcm
  secretKey: HhtaFQcl3sXW6vp85JzkswCRMkcQPymH
  url: http://localhost:9000
  bucket: gulimall
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true
logging:
  level:
    root: info
